### ISSUE TITLE
Docs : Folder Structure

### ISSUE THREAD

**Issue by pranshuchittora** [fnplus/community-project-ideas#3]
Awesome initiative :clap: 

I am not able to find any doc about what folder structure one must follow.

- **Day wise directory** - For each day create a new folder named as `Day${day_count}`.
- **Day wise branch** - For each day one can create a new branch named as `Day-${day_count}`. This approach is quite efficient while cloning & updating the repo.

Let's discuss :speaking_head:

**Comment by xlogix** [comment]
Hey, we're glad you're here!

Did you check out [this](https://github.com/fnplus/100DaysOfCode) repo? The ReadMe.md will clear your doubts on maintaining the log. We're going with a log.md file where you can record your progress!

**Comment by pranshuchittora** [comment]
Ya I read that, but why can't we put the code in the repo along with the log.md so that we can easily refer the source.

**Comment by xlogix** [comment]
We thought project repo would be different and putting the project code in this repo wouldn't be optimum. But, maybe we can link the repo or file in the log?

**Comment by pranshuchittora** [comment]
Sounds great 🤘
